name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unzip project
        run: |
          ZIPFILE=$(find . -maxdepth 1 -iname "*.zip" | head -n 1)
          echo "Found zip: $ZIPFILE"
          unzip -o "$ZIPFILE" -d extracted
          INNER_DIR=$(find extracted -mindepth 1 -maxdepth 1 -type d | head -n 1)
          cp -r "$INNER_DIR"/. .

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 9.3.1

      - name: Build debug APK
        run: gradle assembleDebug --stacktrace --no-configuration-cache --no-daemon
        env:
          GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Djava.awt.headless=true"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk
